# Generated by Django 5.0 on 2025-12-29 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_auto_20251116_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('signature', models.CharField(max_length=255)),
                ('business_name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('primary_color', models.CharField(default='#667eea', max_length=20)),
                ('secondary_color', models.CharField(default='#764ba2', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('provisioned_by', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioning_tokens', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Provisioning Token',
                'verbose_name_plural': 'Provisioning Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetupWizardProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setup_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('setup_token_expires_at', models.DateTimeField()),
                ('step_1_completed', models.BooleanField(default=False)),
                ('step_2_completed', models.BooleanField(default=False)),
                ('step_3_completed', models.BooleanField(default=False)),
                ('step_4_completed', models.BooleanField(default=False)),
                ('step_5_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_progress', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Setup Wizard Progress',
                'verbose_name_plural': 'Setup Wizard Progress',
            },
        ),
    ]
