# Generated by Django 5.0 on 2025-11-09 23:13

import django.core.validators
import django.db.models.deletion
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_uuid', models.CharField(default=tenants.models.generate_tenant_uuid, editable=False, help_text='Unique tenant identifier (e.g., a-cx-3k9f2)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly name for subdomain (e.g., "simifood" for simifood.localhost:8000)', unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')])),
                ('subdomain', models.CharField(db_index=True, help_text='Subdomain for tenant (e.g., "simifood" for simifood.ayendecx.com)', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')])),
                ('description', models.TextField(blank=True, help_text='Brief description of the business')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('CAD', 'Canadian Dollar (C$)'), ('GBP', 'British Pound (£)'), ('EUR', 'Euro (€)'), ('AUD', 'Australian Dollar (A$)'), ('NGN', 'Nigerian Naira (₦)'), ('ZAR', 'South African Rand (R)'), ('KES', 'Kenyan Shilling (KSh)'), ('GHS', 'Ghanaian Cedi (GH₵)'), ('UGX', 'Ugandan Shilling (USh)'), ('TZS', 'Tanzanian Shilling (TSh)'), ('EGP', 'Egyptian Pound (E£)'), ('MAD', 'Moroccan Dirham (DH)'), ('JPY', 'Japanese Yen (¥)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('CHF', 'Swiss Franc (CHF)')], default='USD', help_text='Currency for this business', max_length=3)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol to display (e.g., $, £, ₦, €)', max_length=10)),
                ('currency_position', models.CharField(choices=[('before', 'Before amount ($100)'), ('after', 'After amount (100$)')], default='before', help_text='Where to display currency symbol', max_length=10)),
                ('decimal_places', models.IntegerField(default=2, help_text='Number of decimal places for currency')),
                ('logo', models.ImageField(blank=True, help_text='Business logo', null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#228B22', help_text='Hex color code for primary brand color (e.g., #228B22)', max_length=7)),
                ('secondary_color', models.CharField(default='#FF8C00', help_text='Hex color code for secondary brand color', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this business is active')),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', help_text='Current subscription status', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='When the trial period ends (auto-set to 14 days from creation for new tenants)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Business owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Business Tenant',
                'verbose_name_plural': 'Business Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='tenants.tenant')),
                ('allow_customer_registration', models.BooleanField(default=True, help_text='Allow customers to self-register')),
                ('require_email_verification', models.BooleanField(default=False, help_text='Require email verification for new customers')),
                ('max_customers', models.IntegerField(default=1000, help_text='Maximum number of customers allowed')),
                ('max_staff_members', models.IntegerField(default=10, help_text='Maximum number of staff members')),
                ('enable_loyalty_points', models.BooleanField(default=True, help_text='Enable loyalty points system')),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=1.0, help_text='Points earned per dollar spent', max_digits=5)),
                ('vip_threshold', models.DecimalField(decimal_places=2, default=1000.0, help_text='Spending threshold to automatically qualify as VIP customer', max_digits=10)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Business operating hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
            },
        ),
    ]
