# Generated by Django 5.0 on 2025-10-16 21:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Business name', max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly name for subdomain (e.g., 'simifood' for simifood.ayendecrm.com)", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')])),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the business')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/')),
                ('primary_color', models.CharField(default='#228B22', help_text='Hex color code for primary brand color', max_length=7)),
                ('secondary_color', models.CharField(default='#FF8C00', help_text='Hex color code for secondary brand color', max_length=7)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_starts_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('max_customers', models.IntegerField(default=100, help_text='Maximum number of customers allowed')),
                ('max_storage_gb', models.DecimalField(decimal_places=2, default=5.0, help_text='Maximum storage in GB', max_digits=10)),
                ('max_users', models.IntegerField(default=3, help_text='Maximum number of staff users')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Primary business owner/admin', on_delete=django.db.models.deletion.PROTECT, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Tenant',
                'verbose_name_plural': 'Business Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_push_notifications', models.BooleanField(default=True)),
                ('enable_sms_notifications', models.BooleanField(default=False)),
                ('allow_customer_registration', models.BooleanField(default=True, help_text='Allow customers to register themselves')),
                ('require_email_verification', models.BooleanField(default=True)),
                ('loyalty_points_enabled', models.BooleanField(default=True)),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Store business hours in JSON format')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Custom fields to collect from customers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Settings',
                'verbose_name_plural': 'Tenant Settings',
                'db_table': 'tenant_settings',
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['subscription_status'], name='tenants_subscri_f58e68_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx'),
        ),
    ]
