# Generated by Django 5.0.14 on 2025-10-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="currency",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar ($)"),
                    ("EUR", "Euro (€)"),
                    ("GBP", "British Pound (£)"),
                    ("CAD", "Canadian Dollar (C$)"),
                    ("NGN", "Nigerian Naira (₦)"),
                    ("ZAR", "South African Rand (R)"),
                    ("KES", "Kenyan Shilling (KSh)"),
                    ("GHS", "Ghanaian Cedi (GH₵)"),
                ],
                default="USD",
                help_text="Currency for this business",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="currency_position",
            field=models.CharField(
                choices=[
                    ("before", "Before amount ($100)"),
                    ("after", "After amount (100$)"),
                ],
                default="before",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="currency_symbol",
            field=models.CharField(
                default="$", help_text="Currency symbol to display", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="decimal_places",
            field=models.IntegerField(default=2, help_text="Number of decimal places"),
        ),
    ]
