# Generated by Django 5.0 on 2025-10-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_tenant_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the trial period ends (auto-set to 14 days from creation for new tenants)', null=True),
        ),
    ]
