# Generated by Django 5.0 on 2025-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='birthday_bonus_enabled',
            field=models.BooleanField(default=True, help_text='Send birthday greetings to customers'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='birthday_bonus_points',
            field=models.IntegerField(default=50, help_text='Bonus points awarded on birthday'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='large_purchase_enabled',
            field=models.BooleanField(default=True, help_text='Send thank you message for large purchases'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='large_purchase_threshold',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum purchase amount to trigger thank you message', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='loyalty_milestone_enabled',
            field=models.BooleanField(default=True, help_text='Send congratulations messages on loyalty milestones'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='loyalty_milestones',
            field=models.JSONField(blank=True, default=list, help_text='Point thresholds for milestone messages (e.g., [100, 500, 1000, 2500, 5000])'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='welcome_bonus_enabled',
            field=models.BooleanField(default=True, help_text='Send automated welcome message to new customers'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='welcome_bonus_points',
            field=models.IntegerField(default=100, help_text='Bonus loyalty points awarded on registration'),
        ),
    ]
