# Generated by Django - VIP Threshold Implementation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='vip_threshold',
            field=models.DecimalField(
                decimal_places=2,
                default=1000.0,
                help_text='Spending threshold to automatically qualify as VIP customer',
                max_digits=10
            ),
        ),
    ]
