# Generated by Django 5.0 on 2025-10-20 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(db_index=True, default='', help_text='Subdomain for tenant (e.g., "simifood" for simifood.ayendecx.com)', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Subdomain can only contain lowercase letters, numbers, and hyphens', regex='^[a-z0-9-]+$')]),
            preserve_default=False,
        ),
    ]
