# Generated by Django 5.0 on 2025-11-09 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcustomer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_customers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantcustomer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenants',
            field=models.ManyToManyField(related_name='customers', through='customers.TenantCustomer', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='tenantcustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_accounts', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='sync_logs_status_e8f5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='sync_logs_entity__0b2dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['direction'], name='sync_logs_directi_15d006_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['-created_at'], name='sync_logs_created_a9c4e8_idx'),
        ),
        migrations.AddField(
            model_name='systemmapping',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='system_mappings', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member (TenantCustomer) who processed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant_customer',
            field=models.ForeignKey(blank=True, help_text='Tenant-Customer relationship. Null for anonymous transactions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customers_last_na_89bb5f_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['-created_at'], name='customers_created_beab7c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'username'], name='tenant_cust_tenant__6c780f_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'email'], name='tenant_cust_tenant__420f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_cust_tenant__ffb0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'is_vip'], name='tenant_cust_tenant__a33e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'role'], name='tenant_cust_tenant__47f13b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['loyalty_points'], name='tenant_cust_loyalty_9477aa_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['external_id'], name='tenant_cust_externa_e4d88a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['-date_joined'], name='tenant_cust_date_jo_332bde_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantcustomer',
            unique_together={('tenant', 'username')},
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['entity_type', 'crm_id'], name='system_mapp_entity__bd3a92_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['entity_type', 'pos_id'], name='system_mapp_entity__6070ca_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['tenant'], name='system_mapp_tenant__85cffa_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['entity_type', 'sync_status'], name='system_mapp_entity__a6eab7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemmapping',
            unique_together={('entity_type', 'crm_id'), ('entity_type', 'pos_id')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', 'tenant_customer', '-transaction_date'], name='transaction_tenant__175e9e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant', '-transaction_date'], name='transaction_tenant__c79009_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='transaction_transac_5011c8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_id'], name='transaction_externa_b026b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_source'], name='transaction_externa_2126b4_idx'),
        ),
    ]
