# Generated by Django 5.0 on 2025-10-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcustomer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_customers', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenants',
            field=models.ManyToManyField(related_name='customers', through='customers.TenantCustomer', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'role'], name='tenant_cust_tenant__47f13b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'is_active'], name='tenant_cust_tenant__ffb0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['loyalty_points'], name='tenant_cust_loyalty_9477aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantcustomer',
            unique_together={('customer', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='customers_last_na_89bb5f_idx'),
        ),
    ]
