# Generated by Django 5.0 on 2025-10-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0002_initial'),
        ('tenants', '0003_tenant_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the verification email was last sent', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the email address has been verified'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email_verification_token'], name='customers_email_v_e2bebe_idx'),
        ),
    ]
