# Generated by Django 5.0 on 2025-10-26 20:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0003_customer_email_verification_sent_at_and_more'),
        ('tenants', '0003_tenant_trial_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(help_text="Operation type (e.g., 'transaction_sync')", max_length=50)),
                ('direction', models.CharField(choices=[('pos_to_crm', 'POS to CRM'), ('crm_to_pos', 'CRM to POS')], default='pos_to_crm', max_length=20)),
                ('entity_type', models.CharField(help_text="Entity type (e.g., 'transaction', 'customer')", max_length=50)),
                ('entity_id', models.CharField(help_text='ID of the synced entity', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry Scheduled')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=1)),
                ('error_message', models.TextField(blank=True)),
                ('payload', models.JSONField(help_text='Data that was synced')),
                ('response', models.JSONField(blank=True, help_text='Response from the target system', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('BUSINESS', 'Business'), ('CUSTOMER', 'Customer'), ('TRANSACTION', 'Transaction')], help_text='Type of entity being mapped', max_length=20)),
                ('crm_id', models.CharField(help_text='UUID in CRM system', max_length=255)),
                ('pos_id', models.CharField(help_text='ID in POS system', max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('sync_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Mapping',
                'verbose_name_plural': 'System Mappings',
                'db_table': 'system_mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='tenantcustomer',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='customer',
            name='external_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Customer ID from POS system', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time data was synced from POS', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Transaction ID from POS system', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_source',
            field=models.CharField(choices=[('CRM', 'CRM'), ('POS', 'POS')], default='CRM', help_text='Source system of this transaction', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='synced_at',
            field=models.DateTimeField(blank=True, help_text='When this transaction was synced from POS', null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['external_id'], name='customers_externa_9e76aa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_id'], name='transaction_externa_b026b5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_source'], name='transaction_externa_2126b4_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status'], name='sync_logs_status_e8f5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='sync_logs_entity__0b2dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['direction'], name='sync_logs_directi_15d006_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['-created_at'], name='sync_logs_created_a9c4e8_idx'),
        ),
        migrations.AddField(
            model_name='systemmapping',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant this mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='system_mappings', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['entity_type', 'crm_id'], name='system_mapp_entity__bd3a92_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['entity_type', 'pos_id'], name='system_mapp_entity__6070ca_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['tenant'], name='system_mapp_tenant__85cffa_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmapping',
            index=models.Index(fields=['entity_type', 'sync_status'], name='system_mapp_entity__a6eab7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemmapping',
            unique_together={('entity_type', 'crm_id'), ('entity_type', 'pos_id')},
        ),
    ]
