# Generated by Django 5.0 on 2025-11-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_add_platform_admin_flag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantcustomer',
            options={'ordering': ['-date_joined']},
        ),
        migrations.RenameIndex(
            model_name='tenantcustomer',
            new_name='tenant_cust_is_plat_93d23b_idx',
            old_name='customers_t_is_plat_idx',
        ),
        migrations.AlterField(
            model_name='tenantcustomer',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Administrator'), ('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
