# Generated by Django 5.0 on 2025-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_loyalty_points_customer_loyalty_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.CharField(blank=True, help_text='ID of user who created transaction in POS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='Detailed items list from POS'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_number',
            field=models.CharField(blank=True, help_text='Human-readable transaction number from POS', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='Total amount (amount + tax - discount)', max_digits=10),
        ),
    ]
