# Generated by Django 5.0 on 2025-11-28 19:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_tenantcustomer_options_and_more'),
        ('tenants', '0004_auto_20251116_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, help_text='POS rental contract ID', max_length=100)),
                ('contract_number', models.CharField(db_index=True, max_length=50)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_address', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('expected_return_date', models.DateTimeField()),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('rental_days', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deposit_returned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('damage_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='$', max_length=5)),
                ('currency_code', models.CharField(default='CAD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('overdue', 'Overdue'), ('partially_returned', 'Partially Returned'), ('returned', 'Returned'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('return_notes', models.TextField(blank=True)),
                ('damage_notes', models.TextField(blank=True)),
                ('overdue_notified', models.BooleanField(default=False)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_source', models.CharField(default='POS', max_length=20)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_contracts', to='tenants.tenant')),
                ('tenant_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental Contract',
                'verbose_name_plural': 'Rental Contracts',
                'db_table': 'crm_rental_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalContractItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('returned_quantity', models.IntegerField(default=0)),
                ('damaged_quantity', models.IntegerField(default=0)),
                ('missing_quantity', models.IntegerField(default=0)),
                ('damage_description', models.TextField(blank=True)),
                ('damage_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customers.rentalcontract')),
            ],
            options={
                'verbose_name': 'Rental Contract Item',
                'verbose_name_plural': 'Rental Contract Items',
                'db_table': 'crm_rental_contract_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['tenant', 'status'], name='crm_rental__tenant__07652a_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['tenant', 'expected_return_date'], name='crm_rental__tenant__963d87_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalcontract',
            index=models.Index(fields=['tenant_customer'], name='crm_rental__tenant__5088ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentalcontract',
            unique_together={('tenant', 'external_id')},
        ),
    ]
