# Generated by Django 5.0 on 2025-11-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_rentalcontract_rentalcontractitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalcontract',
            name='damage_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rentalcontract',
            name='return_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
