# Generated by Django - Restore is_vip field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_make_transaction_notes_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcustomer',
            name='is_vip',
            field=models.BooleanField(
                default=False,
                help_text='VIP customer status - automatically set when total_spent exceeds tenant VIP threshold'
            ),
        ),
        migrations.AddIndex(
            model_name='tenantcustomer',
            index=models.Index(fields=['tenant', 'is_vip'], name='tenant_customers_tenant_vip_idx'),
        ),
    ]
