# Generated by Django - Calculate initial VIP status

from django.db import migrations


def calculate_vip_status(apps, schema_editor):
    """Calculate VIP status for all existing customers based on tenant thresholds"""
    TenantCustomer = apps.get_model('customers', 'TenantCustomer')
    TenantSettings = apps.get_model('tenants', 'TenantSettings')
    
    # Process each tenant
    for tenant_settings in TenantSettings.objects.all():
        threshold = tenant_settings.vip_threshold
        tenant = tenant_settings.tenant
        
        # Update all customers for this tenant who meet threshold
        updated_count = TenantCustomer.objects.filter(
            tenant=tenant,
            total_spent__gte=threshold,
            role='customer'
        ).update(is_vip=True)
        
        print(f'[OK] Updated VIP status for {tenant.name} - {updated_count} customers now VIP (threshold: )')


def reverse_vip_status(apps, schema_editor):
    """Reset all VIP statuses to False"""
    TenantCustomer = apps.get_model('customers', 'TenantCustomer')
    TenantCustomer.objects.all().update(is_vip=False)
    print('[ROLLBACK] Reset all VIP statuses to False')


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_tenantcustomer_is_vip'),
        ('tenants', '0004_tenantsettings_vip_threshold'),
    ]

    operations = [
        migrations.RunPython(calculate_vip_status, reverse_vip_status),
    ]