# Generated by Django - Add missing Django auth fields using raw SQL

from django.db import migrations


def add_auth_fields_raw_sql(apps, schema_editor):
    """
    Add Django auth fields using raw SQL to bypass constraint checks.
    """
    from django.db import connection
    
    print("\n" + "="*60)
    print("ADDING DJANGO AUTH FIELDS TO TENANTCUSTOMER")
    print("="*60)
    
    with connection.cursor() as cursor:
        # Disable foreign key checks
        cursor.execute("PRAGMA foreign_keys = OFF")
        
        try:
            # Add is_staff
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN is_staff INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added is_staff")
            
            # Add is_superuser
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN is_superuser INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added is_superuser")
            
            # Add last_login
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN last_login DATETIME NULL
            """)
            print("✅ Added last_login")
            
            # Add date_joined
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN date_joined DATETIME NULL
            """)
            print("✅ Added date_joined")
            
            # Add first_name
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN first_name VARCHAR(150) DEFAULT '' NOT NULL
            """)
            print("✅ Added first_name")
            
            # Add last_name
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN last_name VARCHAR(150) DEFAULT '' NOT NULL
            """)
            print("✅ Added last_name")
            
            print("\n" + "="*60)
            print("AUTH FIELDS ADDED SUCCESSFULLY")
            print("="*60 + "\n")
            
        finally:
            # Re-enable foreign key checks
            cursor.execute("PRAGMA foreign_keys = ON")


def reverse_auth_fields(apps, schema_editor):
    """
    Reverse the migration (for rollback support).
    """
    print("\n⚠️  REVERSING AUTH FIELDS MIGRATION")


class Migration(migrations.Migration):
    
    atomic = False  # Disable atomic transaction

    dependencies = [
        ('customers', '0008_multi_tenant_refactor'),
    ]

    operations = [
        migrations.RunPython(add_auth_fields_raw_sql, reverse_auth_fields),
    ]