# Generated by Django - Add all missing TenantCustomer fields

from django.db import migrations


def add_missing_fields_raw_sql(apps, schema_editor):
    """
    Add all missing fields using raw SQL.
    """
    from django.db import connection
    
    print("\n" + "="*60)
    print("ADDING MISSING FIELDS TO TENANTCUSTOMER")
    print("="*60)
    
    with connection.cursor() as cursor:
        # Disable foreign key checks
        cursor.execute("PRAGMA foreign_keys = OFF")
        
        try:
            # Add profile_picture
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN profile_picture VARCHAR(100) DEFAULT '' NOT NULL
            """)
            print("✅ Added profile_picture")
            
            # Add postal_code
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN postal_code VARCHAR(20) NULL
            """)
            print("✅ Added postal_code")
            
            # Add country
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN country VARCHAR(100) NULL
            """)
            print("✅ Added country")
            
            # Add preferred_language
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN preferred_language VARCHAR(10) DEFAULT 'en' NOT NULL
            """)
            print("✅ Added preferred_language")
            
            # Add email_verified
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN email_verified INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added email_verified")
            
            # Add email_verification_token
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN email_verification_token VARCHAR(64) NULL
            """)
            print("✅ Added email_verification_token")
            
            # Add email_verification_sent_at
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN email_verification_sent_at DATETIME NULL
            """)
            print("✅ Added email_verification_sent_at")
            
            # Add marketing_opt_in
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN marketing_opt_in INTEGER DEFAULT 1 NOT NULL
            """)
            print("✅ Added marketing_opt_in")
            
            # Add needs_enrichment
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN needs_enrichment INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added needs_enrichment")
            
            # Add external_id
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN external_id VARCHAR(255) NULL
            """)
            print("✅ Added external_id")
            
            # Add last_synced_at
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN last_synced_at DATETIME NULL
            """)
            print("✅ Added last_synced_at")
            
            # Add visit_count
            cursor.execute("""
                ALTER TABLE tenant_customers 
                ADD COLUMN visit_count INTEGER DEFAULT 0 NOT NULL
            """)
            print("✅ Added visit_count")
            
            # Add loyalty_tier (this might already exist from migration 0008)
            try:
                cursor.execute("""
                    ALTER TABLE tenant_customers 
                    ADD COLUMN loyalty_tier VARCHAR(20) DEFAULT 'BRONZE' NOT NULL
                """)
                print("✅ Added loyalty_tier")
            except Exception as e:
                print(f"⚠️  loyalty_tier already exists or error: {e}")
            
            # Note: groups and user_permissions are ManyToMany fields and need separate tables
            # They should be handled by Django's migration system automatically
            
            print("\n" + "="*60)
            print("MISSING FIELDS ADDED SUCCESSFULLY")
            print("="*60 + "\n")
            
        finally:
            # Re-enable foreign key checks
            cursor.execute("PRAGMA foreign_keys = ON")


def reverse_missing_fields(apps, schema_editor):
    """
    Reverse the migration (for rollback support).
    """
    print("\n⚠️  REVERSING MISSING FIELDS MIGRATION")


class Migration(migrations.Migration):
    
    atomic = False  # Disable atomic transaction

    dependencies = [
        ('customers', '0009_add_auth_fields'),
    ]

    operations = [
        migrations.RunPython(add_missing_fields_raw_sql, reverse_missing_fields),
    ]
