# Generated by Django - Populate first_name and last_name in TenantCustomer

from django.db import migrations


def populate_names(apps, schema_editor):
    """
    Populate first_name and last_name in TenantCustomer from Customer.
    """
    from django.db import connection
    
    print("\n" + "="*60)
    print("POPULATING FIRST_NAME AND LAST_NAME IN TENANTCUSTOMER")
    print("="*60)
    
    with connection.cursor() as cursor:
        # Update first_name and last_name from customers table
        cursor.execute("""
            UPDATE tenant_customers
            SET first_name = (SELECT first_name FROM customers WHERE customers.id = tenant_customers.customer_id),
                last_name = (SELECT last_name FROM customers WHERE customers.id = tenant_customers.customer_id)
            WHERE customer_id IS NOT NULL
        """)
        
        updated_count = cursor.rowcount
        print(f"\n✅ Updated {updated_count} TenantCustomer records with names")
    
    print("="*60 + "\n")


def reverse_populate_names(apps, schema_editor):
    """
    Reverse the migration.
    """
    print("\n⚠️  REVERSING NAMES POPULATION")


class Migration(migrations.Migration):
    
    atomic = False  # Disable atomic transaction

    dependencies = [
        ('customers', '0010_add_missing_fields'),
    ]

    operations = [
        migrations.RunPython(populate_names, reverse_populate_names),
    ]
