# Generated by Django 5.0 on 2025-12-28 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('investment_amount', models.CharField(choices=[('5000', '$5,000 (Believer)'), ('10000', '$10,000 (Early Supporter)'), ('25000', '$25,000+ (Founding Circle)')], help_text='Intended investment amount', max_length=10)),
                ('accredited_investor', models.BooleanField(default=False, help_text='Certified accredited investor status')),
                ('status', models.CharField(choices=[('new', 'New Lead'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('negotiating', 'Negotiating'), ('converted', 'Converted'), ('lost', 'Lost'), ('on_hold', 'On Hold')], db_index=True, default='new', max_length=20)),
                ('lead_score', models.IntegerField(default=0, help_text='Auto-calculated score (0-100)')),
                ('priority', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], db_index=True, default='warm', max_length=10)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, db_index=True, help_text='Suggested next follow-up date', null=True)),
                ('follow_up_count', models.IntegerField(default=0, help_text='Number of follow-up attempts')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('referral', 'Referral'), ('direct', 'Direct Contact'), ('event', 'Event'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='website', max_length=50)),
                ('referral_source', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual converted investment amount', max_digits=10, null=True)),
                ('lost_reason', models.TextField(blank=True, help_text='Reason if lead was lost')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Sales team member assigned to this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_investment_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Lead',
                'verbose_name_plural': 'Investment Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('email', 'Email'), ('call', 'Phone Call'), ('meeting', 'Meeting'), ('note', 'Note'), ('status_change', 'Status Change'), ('document_sent', 'Document Sent'), ('follow_up', 'Follow-up')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('no_response', 'No Response')], help_text='Outcome of the activity', max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='investment.investmentlead')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Activity',
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this note to the top')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_notes', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='investment.investmentlead')),
            ],
            options={
                'verbose_name': 'Lead Note',
                'verbose_name_plural': 'Lead Notes',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='investmentlead',
            index=models.Index(fields=['-created_at', 'status'], name='investment__created_d6b5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentlead',
            index=models.Index(fields=['priority', '-lead_score'], name='investment__priorit_52a366_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentlead',
            index=models.Index(fields=['assigned_to', 'status'], name='investment__assigne_de973f_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-performed_at'], name='investment__lead_id_6ad8e4_idx'),
        ),
    ]
